---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: roboshop-ebs
  accessModes:
  - ReadWriteOnce
  resources:  
    requests:
      storage: 7Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-static
spec:
  containers:
    - name: nginx 
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: html-data
  volumes:
    - name: html-data
      persistentVolumeClaim:
        claimName: roboshop-ebs # Must match the name of your PVC

  nodeSelector:
    topology.kubernetes.io/zone:  us-east-1d
