# install efs driver
#efs driver--> kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"
# allow AmazonEFSCSIDriverPolicy IAM policy  for instance's SG
# allow EFS file SG with 2049 port and instances SG as both inbound and outbound

apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  capacity:
    storage: 5Gi #it ignores as it is EFS
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "" # sc should be empty for static provisioning
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-045d8b890635d7877

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: html-data
      mountPath: /usr/share/nginx/html
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d
  volumes:
  - name: html-data
    persistentVolumeClaim:
      claimName: efs-static