kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-roboshop
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-045d8b890635d7877 # Replace with your EFS ID
  directoryPerms: "700"
  basePath: "/roboshop" # Optional: Subdirectory in EFS for volumes