apiVersion: v1
kind: Namespace
metadata:
    name: roboshop
    labels:
      project: roboshop
      environment: dev


---

apiVersion: v1
kind: Namespace
metadata:
  name: practice
  labels:
    purpose: practice
    env: non-prod
    
