apiVersion: v1 
kind: Pod
metadata:
    name: robo-pod
    labels:
      env: dev
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
    
---
apiVersion: v1
kind: Secret 
metadata:
  name: pod-expose-secret

spec:
  selector:
    env: dev
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP




