apiVersion: v1 
kind: Pod
metadata:
    name: annotation-pod
    namespace: practice
    labels:
      env: dev
      project: roboshop
    annotations:
      dockerURL: "http://docker.com"
      jenkinsURL: "https://jenkins.io"
      jfrogURL: "https://jfrog.com"

spec:
  containers:
    - name: nginx
      image: nginx
